### ISSUE TITLE
pdf_extrac/__init__.py 出现问题

### ISSUE THREAD

**Issue by Canqiang** [MasterYip/ChatPaper2Xmind#1]
![image](https://github.com/MasterYip/ChatPaper2Xmind/assets/44384776/b7881b90-479d-42af-b409-c6d75de0414a)

TypeError: 'type' object is not subscriptable

python 的tuple类不能这么用

**Comment by MasterYip** [comment]
在Python中，tuple［4］的用法在3.9版本及更早的版本上会报错。这是因为在3.9版本之前，Python并不支持通过内置类型提示来指定具有特定长度的元组（Fixed-Length Tuple）。在3.9版本中，引入了PEP 585，支持使用内置的Fixed-Length Tuple类型提示。

在Python 3.9更早版本中，如果你尝试使用"tuple［4］"这样的类型提示，会导致语法错误。
PEP585详见https://peps.python.org/pep-0585/

**Comment by Canqiang** [comment]
好的，感谢回复

**Comment by MasterYip** [comment]
哈哈 感谢提醒 到时候打算做个免环境发布版本，会支持到3.8

**Comment by Canqiang** [comment]
非常棒的项目！目前好像部分期刊类似于nature/cell/等PDF解析会有问题，我这边遇到了报错
![image](https://github.com/MasterYip/ChatPaper2Xmind/assets/44384776/f61040d1-3416-49e8-827a-40d89d8f2f7e)

**Comment by MasterYip** [comment]
嗯 好的，会尽快处理~

**Comment by MasterYip** [comment]
如果有兴趣的话，欢迎合作：）

**Comment by Canqiang** [comment]
好呀，您邮箱方便吗，我将WeChatID发您邮箱，或者您可以类似GLM2-6B这样的项目组个微信群，把群二维码放在项目里
