### ISSUE TITLE
这个报错怎么解决

### ISSUE THREAD

**Issue by moshangchenkai** [MasterYip/ChatPaper2Xmind#5]
D:\academic chatgpt series\ChatPaper2Xmind-main>python paper2xmind.py --path "D:\academic chatgpt series\ChatPaper-main\demo.pdf"
Traceback (most recent call last):
  File "D:\academic chatgpt series\ChatPaper2Xmind-main\paper2xmind.py", line 3, in <module>
    from XmindCopilot import xmind, fileshrink
ImportError: cannot import name 'xmind' from 'XmindCopilot' (unknown location)

**Comment by MasterYip** [comment]
请确保此条命令正确执行

git clone --recursive https://github.com/MasterYip/ChatPaper2Xmind.git

原因可能是你下载了zip压缩包，这并不包含XmindCopilot仓库。

**Comment by moshangchenkai** [comment]
现在我配置好了的。但是又有新报错。
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Exception ignored in: <function PDFPaperParser.__del__ at 0x000001F4388C2C00>
Traceback (most recent call last):
  File "D:\git\ChatPaper2Xmind\pdf_parser.py", line 31, in __del__
    self.pdf.close()
    ^^^^^^^^
AttributeError: 'PDFFigure2PaperParser' object has no attribute 'pdf'

**Comment by MasterYip** [comment]
可能是你的PDF文件路径输入有误，导致PDF文件没有找到。可以尝试运行readme中的示例，检查是否能正常运行
