### ISSUE TITLE
报错，怎么修改，显示超过token限制

### ISSUE THREAD

**Issue by shenycs** [MasterYip/ChatPaper2Xmind#7]
he server is overloaded or not ready yet.
 30%|████████████████████████▍                                                         | 14/47 [07:54<18:08, 32.99s/it]This model's maximum context length is 4097 tokens. However, your messages resulted in 13348 tokens. Please reduce the length of the messages.
This model's maximum context length is 4097 tokens. However, your messages resulted in 13348 tokens. Please reduce the length of the messages.
This model's maximum context length is 4097 tokens. However, your messages resulted in 13348 tokens. Please reduce the length of the messages.

**Comment by MasterYip** [comment]
目前还没有特别好的解决方法😂
目前可以采取截断的方法，在gpt interface文件当中openai.chatcompletion请求内容超过4096 token的部分截断
关于token计算可以参考tokenizer tiktoken等库

修改完后欢迎pull request~
